{- Even Fibonacci Numbers
 - Each new term in the Fibonacci sequence is generated by adding the previous
 - two terms. By Starting with 1 and 2, the first 10 terms will be:
 -              
 -              1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 -
 - By considering the terms in the Fibonacci sequence whose values do not
 - exceed four million, find the sum of the even-valued terms.
 -
 -
 - Create a lazy list of all Fibonacci numbers.
 - Generate a lazy list of the even ones.
 - Add all even Fibonacci numbers below N.
-}

fib :: [Integer]
fib = 0 : 1 : [a + b | (a,b) <- zip fib (tail fib)]

evenFib :: [Integer]
evenFib = [x | x <- fib, x `mod` 2 == 0]

sumEvenFib :: Integer -> Integer
sumEvenFib n = sum (takeWhile (<= n) evenFib)
